import React, { useState } from 'react';
import { Cpu, Activity, PlayCircle, Copy, Check, RefreshCw, Sliders } from 'lucide-react';
import type { HardwareProfile, HardwareSimulation } from '../types/hardware';

interface NavbarProps {
  hardware: HardwareProfile | null;
  simulation: HardwareSimulation;
  onToggleSimulator: () => void;
  onRefreshHardware: () => void;
  onOpenBenchmark: () => void;
  onOpenInference: () => void;
}

export const Navbar: React.FC<NavbarProps> = ({
  hardware,
  simulation,
  onToggleSimulator,
  onRefreshHardware,
  onOpenBenchmark,
  onOpenInference,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopySpecs = () => {
    if (!hardware) return;

    const specsMarkdown = `### Device AI Hardware Profile
- **OS / Platform**: ${hardware.os} (${hardware.platform})
- **Browser**: ${hardware.browser}
- **CPU Cores**: ${hardware.cpuCores} (${hardware.cpuArchitecture})
- **RAM**: ${hardware.reportedRamGB ? `${hardware.reportedRamGB} GB (reported)` : `~${hardware.estimatedRamGB} GB (estimated)`}
- **WebGPU Supported**: ${hardware.hasWebGPU ? 'Yes' : 'No'}
- **GPU Adapter**: ${hardware.webgpuDevice || hardware.webglRenderer}
- **shader-f16 Support**: ${hardware.hasShaderF16 ? 'Yes' : 'No'}
- **Max Storage Buffer**: ${hardware.webgpuLimits ? `${Math.round(hardware.webgpuLimits.maxStorageBufferBindingSize / (1024 * 1024))} MB` : 'N/A'}
- **WASM SIMD**: ${hardware.hasWasmSimd ? 'Supported' : 'Unsupported'}
- **Available Storage**: ${hardware.storageAvailableGB ?? 'Unknown'} GB
- **Downlink Speed**: ${hardware.downlinkMbps ? `${hardware.downlinkMbps} Mbps` : 'Unknown'}
- **Chrome Built-in AI**: ${hardware.hasChromeBuiltinAI ? hardware.chromeBuiltinAIStatus : 'Disabled / Unavailable'}
*Generated by LLM Locally Hardware Explorer*`;

    navigator.clipboard.writeText(specsMarkdown).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  return (
    <header className="sticky top-0 z-40 w-full backdrop-blur-md bg-slate-950/85 border-b border-slate-800/80 transition-all">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
        {/* Logo & Title */}
        <div className="flex items-center space-x-3">
          <div className="h-10 w-10 rounded-xl bg-gradient-to-tr from-cyan-500 to-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-500/20 text-white font-bold text-lg">
            <Cpu className="h-6 w-6 text-white" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <span className="font-extrabold text-xl tracking-tight bg-gradient-to-r from-white via-slate-100 to-slate-400 bg-clip-text text-transparent">
                LLM Locally
              </span>
              <span className="text-[10px] uppercase font-semibold tracking-wider px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-400 border border-cyan-800">
                WebGPU & WASM
              </span>
            </div>
            <p className="text-xs text-slate-400 hidden sm:block">
              Hardware Profiler & In-Browser AI Compatibility Matrix
            </p>
          </div>
        </div>

        {/* Live Hardware Status Pill */}
        <div className="hidden lg:flex items-center space-x-2 px-3 py-1.5 rounded-full bg-slate-900 border border-slate-800 text-xs">
          {simulation.isActive ? (
            <span className="flex items-center space-x-1.5 text-amber-400 font-medium">
              <span className="h-2 w-2 rounded-full bg-amber-400 animate-pulse"></span>
              <span>Simulating: {simulation.presetName || `${simulation.ramGB}GB RAM, ${simulation.gpuBackend}`}</span>
            </span>
          ) : hardware ? (
            <span className="flex items-center space-x-1.5 text-emerald-400 font-medium">
              <span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"></span>
              <span className="text-slate-300">
                {hardware.hasWebGPU ? (
                  <>
                    <span className="text-emerald-400 font-semibold">WebGPU Active</span>
                    {hardware.hasShaderF16 && <span className="text-cyan-400 ml-1 font-mono text-[11px]">(f16)</span>}
                    <span className="text-slate-400 ml-1">• {hardware.reportedRamGB || hardware.estimatedRamGB}GB RAM</span>
                  </>
                ) : (
                  <span className="text-amber-400">WASM / CPU Only (No WebGPU)</span>
                )}
              </span>
            </span>
          ) : (
            <span className="text-slate-400">Detecting hardware...</span>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex items-center space-x-2">
          {/* Simulator Toggle */}
          <button
            onClick={onToggleSimulator}
            className={`flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all border ${
              simulation.isActive
                ? 'bg-amber-500/20 text-amber-300 border-amber-500/40 hover:bg-amber-500/30'
                : 'bg-slate-900 text-slate-300 border-slate-700 hover:bg-slate-800 hover:text-white'
            }`}
            title="Configure custom hardware specs or test other device presets"
          >
            <Sliders className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">{simulation.isActive ? 'Simulator Active' : 'Simulate Hardware'}</span>
          </button>

          {/* Live In-Browser Test */}
          <button
            onClick={onOpenInference}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-indigo-600/20 text-indigo-300 border border-indigo-500/30 hover:bg-indigo-600/30 hover:text-indigo-200 transition-all"
            title="Run real live inference in this browser tab"
          >
            <PlayCircle className="h-3.5 w-3.5 text-indigo-400" />
            <span className="hidden md:inline">Live Model Test</span>
          </button>

          {/* WebGPU Stress Test */}
          <button
            onClick={onOpenBenchmark}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-cyan-600/20 text-cyan-300 border border-cyan-500/30 hover:bg-cyan-600/30 hover:text-cyan-200 transition-all"
            title="Run live WebGPU memory and compute benchmarks"
          >
            <Activity className="h-3.5 w-3.5 text-cyan-400" />
            <span className="hidden md:inline">GPU Stress Test</span>
          </button>

          {/* Copy Markdown Report */}
          <button
            onClick={handleCopySpecs}
            className="p-1.5 rounded-lg bg-slate-900 text-slate-400 hover:text-white border border-slate-800 hover:border-slate-700 transition-all"
            title="Copy Device Hardware Report as Markdown"
          >
            {copied ? <Check className="h-4 w-4 text-emerald-400" /> : <Copy className="h-4 w-4" />}
          </button>

          {/* Refresh Hardware */}
          <button
            onClick={onRefreshHardware}
            className="p-1.5 rounded-lg bg-slate-900 text-slate-400 hover:text-white border border-slate-800 hover:border-slate-700 transition-all"
            title="Re-scan device hardware"
          >
            <RefreshCw className="h-4 w-4" />
          </button>
        </div>
      </div>
    </header>
  );
};
