import React, { useState } from 'react';
import { Copy, Check, RefreshCw, Sliders, Activity, Play } from 'lucide-react';
import type { HardwareProfile, HardwareSimulation } from '../types/hardware';

interface NavbarProps {
  hardware: HardwareProfile | null;
  simulation: HardwareSimulation;
  onToggleSimulator: () => void;
  onRefreshHardware: () => void;
  onOpenBenchmark: () => void;
  onOpenInference: () => void;
}

export const Navbar: React.FC<NavbarProps> = ({
  hardware,
  simulation,
  onToggleSimulator,
  onRefreshHardware,
  onOpenBenchmark,
  onOpenInference,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopySpecs = () => {
    if (!hardware) return;

    const specsMarkdown = `### Device AI Hardware Profile
- **OS / Platform**: ${hardware.os} (${hardware.platform})
- **Browser**: ${hardware.browser}
- **CPU Cores**: ${hardware.cpuCores} (${hardware.cpuArchitecture})
- **RAM**: ${hardware.reportedRamGB ? `${hardware.reportedRamGB} GB (reported)` : `~${hardware.estimatedRamGB} GB (estimated)`}
- **WebGPU Supported**: ${hardware.hasWebGPU ? 'Yes' : 'No'}
- **GPU Adapter**: ${hardware.webgpuDevice || hardware.webglRenderer}
- **shader-f16 Support**: ${hardware.hasShaderF16 ? 'Yes' : 'No'}
- **Max Storage Buffer**: ${hardware.webgpuLimits ? `${Math.round(hardware.webgpuLimits.maxStorageBufferBindingSize / (1024 * 1024))} MB` : 'N/A'}
- **WASM SIMD**: ${hardware.hasWasmSimd ? 'Supported' : 'Unsupported'}
- **Available Storage**: ${hardware.storageAvailableGB ?? 'Unknown'} GB
- **Downlink Speed**: ${hardware.downlinkMbps ? `${hardware.downlinkMbps} Mbps` : 'Unknown'}
- **Chrome Built-in AI**: ${hardware.hasChromeBuiltinAI ? hardware.chromeBuiltinAIStatus : 'Disabled / Unavailable'}
*Generated by LLM Locally*`;

    navigator.clipboard.writeText(specsMarkdown).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <header className="sticky top-0 z-40 w-full bg-[#000000]/90 backdrop-blur-md border-b border-[#262626]">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 h-14 flex items-center justify-between">
        {/* Left: Brand / Title */}
        <div className="flex items-center space-x-3">
          {/* Vercel-style geometric triangle logo */}
          <div className="h-6 w-6 flex items-center justify-center text-white">
            <svg viewBox="0 0 76 65" height="18" fill="currentColor">
              <path d="M37.5274 0L75.0548 65H0L37.5274 0Z" fill="#FFFFFF" />
            </svg>
          </div>
          
          <div className="flex items-center space-x-2.5">
            <span className="text-sm font-semibold tracking-[-0.28px] text-[#EDEDED]">
              llm-locally
            </span>
            <span className="text-[#333333]">/</span>
            <span className="text-xs font-normal text-[#8F8F8F] hidden sm:inline">
              device hardware matrix
            </span>
          </div>
        </div>

        {/* Center: Device State indicator */}
        <div className="hidden md:flex items-center space-x-2 text-xs font-normal text-[#A1A1A1]">
          {simulation.isActive ? (
            <span className="flex items-center space-x-2 px-2.5 py-1 rounded-full bg-[#171717] border border-[#333333]">
              <span className="w-2 h-2 rounded-full bg-[#FF990A]"></span>
              <span>Simulation: {simulation.presetName || `${simulation.ramGB}GB RAM`}</span>
            </span>
          ) : hardware ? (
            <span className="flex items-center space-x-2 px-2.5 py-1 rounded-full bg-[#111111] border border-[#262626]">
              <span className={`w-2 h-2 rounded-full ${hardware.hasWebGPU ? 'bg-[#398E4A]' : 'bg-[#FF990A]'}`}></span>
              <span>
                {hardware.hasWebGPU ? 'WebGPU Active' : 'WASM CPU Fallback'}
                {hardware.hasShaderF16 && ' (f16)'}
                <span className="text-[#707070] ml-1.5">• {hardware.reportedRamGB || hardware.estimatedRamGB}GB RAM</span>
              </span>
            </span>
          ) : (
            <span className="text-[#707070]">Probing system...</span>
          )}
        </div>

        {/* Right: Actions */}
        <div className="flex items-center space-x-1.5">
          <button
            onClick={onToggleSimulator}
            className={`h-8 px-3 rounded-md text-xs font-medium transition-colors border flex items-center gap-1.5 ${
              simulation.isActive
                ? 'bg-[#171717] text-[#EDEDED] border-[#4D4D4D]'
                : 'bg-transparent text-[#A1A1A1] hover:text-[#EDEDED] border-[#262626] hover:bg-[#121212]'
            }`}
          >
            <Sliders className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Simulator</span>
          </button>

          <button
            onClick={onOpenInference}
            className="h-8 px-3 rounded-md text-xs font-medium bg-transparent text-[#A1A1A1] hover:text-[#EDEDED] border border-[#262626] hover:bg-[#121212] transition-colors flex items-center gap-1.5"
          >
            <Play className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">Run Model</span>
          </button>

          <button
            onClick={onOpenBenchmark}
            className="h-8 px-3 rounded-md text-xs font-medium bg-transparent text-[#A1A1A1] hover:text-[#EDEDED] border border-[#262626] hover:bg-[#121212] transition-colors flex items-center gap-1.5"
          >
            <Activity className="h-3.5 w-3.5" />
            <span className="hidden sm:inline">GPU Test</span>
          </button>

          <button
            onClick={handleCopySpecs}
            className="h-8 w-8 rounded-md bg-transparent text-[#A1A1A1] hover:text-[#EDEDED] border border-[#262626] hover:bg-[#121212] transition-colors flex items-center justify-center"
            title="Copy Specs as Markdown"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-[#398E4A]" /> : <Copy className="h-3.5 w-3.5" />}
          </button>

          <button
            onClick={onRefreshHardware}
            className="h-8 w-8 rounded-md bg-transparent text-[#A1A1A1] hover:text-[#EDEDED] border border-[#262626] hover:bg-[#121212] transition-colors flex items-center justify-center"
            title="Re-scan device hardware"
          >
            <RefreshCw className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>
    </header>
  );
};
